clear;
clc;
addpath(genpath('.'));
load 'climateP17';
ratio = 0.1;
lambdas = [-3,3,10];
[Dat_eval , Dat_test] = MTGL_Datpre(series,ratio); 
[W,opt_lambda,train_time] = MTGL_Crosval(Dat_eval.X, Dat_eval.Y, 'Lasso',lambdas);
Quality = MTGL_Test(Dat_test.X, Dat_test.Y, W);
save('MTGL_climate_rst.mat','Quality','train_time','opt_lambda');
exit;